name: Code style

on:
  push:
    branches: [main, features]
  pull_request:
    branches: [main, features]

jobs:
  lint:
    runs-on: ubuntu-latest

    name: Code Style
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - uses: psf/black@20.8b1
