name: Tests

on:
  push:
    branches: [main, features]
  pull_request:
    branches: [main, features]

jobs:
  doc-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
          - macos-10.15
          - macos-11.0
          - windows-2019
        python_version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'

    name: Doc tests (Python ${{ matrix.python_version }} on ${{ matrix.os }})
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
        architecture: x64
