name: Release Application

on:
  push:
    tags: ['v*']

jobs:
  pipy:
    name: Release to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install build dependencies
        run: |
          poetry install
      - name: Build and publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_PASSWORD }}
        run: |
          poetry build
          poetry publish
