name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  doc-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python_version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'

    name: Python ${{ matrix.python_version }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python_version }}
        architecture: x64

    - name: Prepare environment
      run: |
        python3 -mpip install -U pip poetry
        poetry install

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        poetry run coverage run tests.py

    - name: Analyze coverage
      run: |
        poetry run coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_PARALLEL: true
        COVERALLS_FLAG_NAME: "Py${{ matrix.python_version }}_${{ matrix.os }}"

  coverage:
    name: Push coverage report
    needs: doc-tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Prepare Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -U pip poetry
          poetry install

      - name: Upload coverage report
        run: |
          poetry run coveralls --finish --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
