name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  doc-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python_version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'

    name: Python ${{ matrix.python_version }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
        architecture: x64

    - name: Prepare environment
      run: |
        python3 -mpip install -U pip poetry
        poetry install

    - name: Run tests (with coverage)
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.python_version == '3.10' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        poetry run coverage run tests.py
        poetry run coveralls --service=github

    - name: Run tests (without coverage)
      if: ${{ matrix.os != 'ubuntu-latest' || matrix.python_version != '3.10' }}
      run: |
        make tests
